"""Embed image descriptions and insert into vector index.

Reads image_chunks.jsonl (generated by build_image_chunks.py), embeds each
description with bge-m3, and inserts synthetic chunks into index.sqlite so
image descriptions participate in vector retrieval alongside text chunks.

Usage:
    python scripts/embed_image_chunks.py
"""

from __future__ import annotations

import json
import re
import sqlite3
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

KB_DIR = PROJECT_ROOT / "data" / "processed" / "kb"
DB_PATH = KB_DIR / "index.sqlite"
IMAGE_CHUNKS_PATH = KB_DIR / "image_chunks.jsonl"
IMAGES_PATH = KB_DIR / "images.jsonl"

IMAGE_CHUNK_PREFIX = "img:"


def load_image_metadata() -> dict[str, dict]:
    """image_id -> {referenced_by, file_name, path} from images.jsonl"""
    mapping = {}
    with open(IMAGES_PATH, "r", encoding="utf-8") as f:
        for line in f:
            rec = json.loads(line)
            mapping[rec["image_id"]] = {
                "referenced_by": rec.get("referenced_by", []),
                "file_name": rec.get("file_name", ""),
                "path": rec.get("path", ""),
            }
    return mapping


def extract_product_from_description(desc: str) -> str:
    """Extract product name from [Product] prefix in description."""
    m = re.match(r"\[([^\]]+)\]", desc)
    if m:
        return m.group(1)
    return ""


def _delegate_to_rebuild() -> bool:
    """If DashScope mode is active, delegate to the full rebuild script."""
    try:
        from industry_agent.config import settings as _s
        if _s.dashscope_enabled:
            print("DashScope mode — delegating to rebuild_vectors_dashscope.py")
            import subprocess
            subprocess.check_call(
                [sys.executable, str(PROJECT_ROOT / "scripts" / "rebuild_vectors_dashscope.py")]
            )
            return True
    except ImportError:
        pass
    return False


def main():
    if _delegate_to_rebuild():
        return
    print("Loading image metadata...")
    image_meta = load_image_metadata()
    print(f"  {len(image_meta)} images in index")

    print("Loading image descriptions...")
    image_descriptions = {}
    with open(IMAGE_CHUNKS_PATH, "r", encoding="utf-8") as f:
        for line in f:
            rec = json.loads(line)
            image_descriptions[rec["image_id"]] = rec["description"]
    print(f"  {len(image_descriptions)} image descriptions")

    # Only embed images that exist in both
    common_ids = set(image_descriptions) & set(image_meta)
    print(f"  {len(common_ids)} images present in both")

    print("Loading embedding model (bge-m3)...")
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer("BAAI/bge-m3")
    print(f"  Model loaded, dim={model.get_sentence_embedding_dimension()}")

    # Connect to DB
    conn = sqlite3.connect(str(DB_PATH))

    # Remove any previously inserted image chunks (idempotent)
    existing = conn.execute(
        "SELECT COUNT(*) FROM chunks WHERE chunk_id LIKE ?",
        (f"{IMAGE_CHUNK_PREFIX}%",),
    ).fetchone()[0]
    if existing:
        print(f"  Removing {existing} existing image chunks...")
        conn.execute("DELETE FROM chunks WHERE chunk_id LIKE ?", (f"{IMAGE_CHUNK_PREFIX}%",))
        conn.execute("DELETE FROM chunk_vectors WHERE chunk_id LIKE ?", (f"{IMAGE_CHUNK_PREFIX}%",))
        conn.commit()

    # Build synthetic chunks
    chunks_to_insert = []
    vectors_to_insert = []

    for image_id in sorted(common_ids):
        desc = image_descriptions[image_id]
        meta = image_meta[image_id]

        # Determine product name (strip "手册" suffix to match regular chunks)
        product = extract_product_from_description(desc)
        if not product and meta["referenced_by"]:
            product = meta["referenced_by"][0]
        product = product.replace("手册", "")

        # Determine manual_id
        if meta["referenced_by"]:
            manual_id = meta["referenced_by"][0]
        else:
            manual_id = product if product else "unknown"

        chunk_id = f"{IMAGE_CHUNK_PREFIX}{image_id}"
        source_path = meta.get("path", "")

        # Embed the description
        vector = model.encode([desc], normalize_embeddings=True)[0]
        vector_blob = _encode_vector([float(v) for v in vector])

        chunks_to_insert.append((
            chunk_id,
            manual_id,
            product,
            source_path,
            f"[Image] {image_id}",
            desc,
            json.dumps([image_id], ensure_ascii=False),
            0,  # section_index
            9999,  # chunk_index
            len(desc),
            json.dumps({"is_image_chunk": True}, ensure_ascii=False),
        ))

        vectors_to_insert.append((
            chunk_id,
            "BAAI/bge-m3",
            1024,
            vector_blob,
        ))

    # Batch insert
    print(f"  Inserting {len(chunks_to_insert)} image chunks...")
    conn.executemany(
        """
        INSERT INTO chunks (
          chunk_id, manual_id, product_name, source_path, title, text,
          image_ids, section_index, chunk_index, char_count, metadata
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        chunks_to_insert,
    )

    conn.executemany(
        """
        INSERT INTO chunk_vectors (chunk_id, embedding_model, dimensions, vector)
        VALUES (?, ?, ?, ?)
        """,
        vectors_to_insert,
    )

    conn.commit()

    # Verify
    count = conn.execute(
        "SELECT COUNT(*) FROM chunks WHERE chunk_id LIKE ?",
        (f"{IMAGE_CHUNK_PREFIX}%",),
    ).fetchone()[0]
    vec_count = conn.execute(
        "SELECT COUNT(*) FROM chunk_vectors WHERE chunk_id LIKE ?",
        (f"{IMAGE_CHUNK_PREFIX}%",),
    ).fetchone()[0]

    print(f"  Done: {count} chunks, {vec_count} vectors inserted")

    # Show a few samples
    print("\n--- Sample image chunks ---")
    samples = conn.execute(
        "SELECT chunk_id, product_name, substr(text, 1, 120) as preview FROM chunks WHERE chunk_id LIKE ? LIMIT 5",
        (f"{IMAGE_CHUNK_PREFIX}%",),
    ).fetchall()
    for row in samples:
        print(f"  {row[0]} [{row[1]}] {row[2]}...")

    conn.close()
    print("\nImage chunks embedded successfully.")


def _encode_vector(vector: list[float]) -> bytes:
    import struct
    return struct.pack(f"<{len(vector)}f", *vector)


if __name__ == "__main__":
    main()
